### ISSUE TITLE
[bug] cannot set source dir

### ISSUE THREAD

**Issue by Freed-Wu** [BSFishy/meson-build#24]
For `source_dir` is not `.`:

```sh
meson setup build_dir source_dir
```

```yaml
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          setup-option: source_dir
```

cannot work.
