### ISSUE TITLE
string escape problem on windows

### ISSUE THREAD

**Issue by bugQ** [BSFishy/meson-build#9]
when using this workflow:
```
name: Build for Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.4.1

    - name: Build with Meson
      uses: BSFishy/meson-build@v1.0.2
      with:
        action: build

    # ...
```
we get this error:
```
Found ninja.EXE-1.8.2 at "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.EXE"
Error: Unable to locate executable file: C:\Program. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.
```
